#!/bin/bash

# Install a JupyterLab extension for demonstration purposes
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install ipyaggrid --minimize=False
jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimize=False
jupyter labextension install bqplot --minimize=False
